# Generated by Django 5.2.17 on 2026-09-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(editable=False, max_length=50, unique=True)),
                ('direccion_destino', models.CharField(default='Dirección por defecto', max_length=255)),
                ('estado', models.CharField(choices=[('REGISTRADO', 'Registrado'), ('EN_CAMINO', 'En camino'), ('ENTREGADO', 'Entregado')], default='REGISTRADO', max_length=30)),
                ('eta_estimado', models.CharField(default='45 minutos (estimado)', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
