# Generated by Django 6.1.1 on 2026-09-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='detalles_plan',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pedido',
            name='medio_transporte',
            field=models.CharField(default='No asignado', max_length=50),
        ),
        migrations.AddField(
            model_name='pedido',
            name='motivo_asignacion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
